import { PrismaClient, PricingType } from '@prisma/client'

const prisma = new PrismaClient()

const gf = (domain: string) =>
  `https://www.google.com/s2/favicons?domain=${domain}&sz=256`

const categories = [
  { name: 'Text Generation', slug: 'text-generation', description: 'AI tools for generating, editing, and improving text content', icon: '✍️' },
  { name: 'Image Generation', slug: 'image-generation', description: 'Create stunning images and artwork from text descriptions', icon: '🎨' },
  { name: 'Video Generation', slug: 'video-generation', description: 'Generate and edit videos with AI-powered tools', icon: '🎬' },
  { name: 'Music Generation', slug: 'music-generation', description: 'Compose and generate music tracks using artificial intelligence', icon: '🎵' },
  { name: 'Presentation Creation', slug: 'presentation-creation', description: 'Create beautiful presentations and slides with AI assistance', icon: '📊' },
  { name: 'Programming', slug: 'programming', description: 'AI coding assistants and developer tools', icon: '💻' },
  { name: 'Translation', slug: 'translation', description: 'Translate text and documents between languages accurately', icon: '🌍' },
  { name: 'Voice & Speech', slug: 'voice-speech', description: 'Text-to-speech, voice cloning, and speech recognition tools', icon: '🎙️' },
  { name: 'Document Processing', slug: 'document-processing', description: 'Analyze, summarize, and extract information from documents', icon: '📄' },
  { name: 'Chatbots', slug: 'chatbots', description: 'Conversational AI assistants for various tasks', icon: '🤖' },
  { name: 'Data Analytics', slug: 'data-analytics', description: 'Analyze data and generate insights with AI assistance', icon: '📈' },
]

const tools = [
  {
    name: 'ChatGPT',
    slug: 'chatgpt',
    logo: gf('chat.openai.com'),
    websiteUrl: 'https://chat.openai.com',
    description: 'ChatGPT is an AI-powered chatbot by OpenAI capable of generating human-like text for writing, analysis, coding, and answering questions. One of the most widely used AI assistants in the world.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Highly versatile', 'Strong reasoning capabilities', 'Large context window', 'Plugin and tool ecosystem', 'Regular model updates'],
    cons: ['Can hallucinate facts', 'Free tier has rate limits', 'Requires Plus for GPT-4o', 'No real-time internet on free tier'],
    alternatives: ['claude', 'gemini', 'perplexity'],
    usageInstructions: 'Visit chat.openai.com and sign up for a free account. Type your query in the message box. Use custom instructions to set persistent preferences. Upgrade to Plus for GPT-4o access.',
    featured: true,
    translations: {
      ru: {
        description: 'ChatGPT — мощный чат-бот с ИИ от OpenAI, способный генерировать человекоподобный текст для написания, анализа, программирования и ответов на вопросы. Один из самых популярных ИИ-ассистентов в мире.',
        pros: ['Очень универсален', 'Сильные способности к рассуждению', 'Большое контекстное окно', 'Экосистема плагинов и инструментов', 'Регулярные обновления модели'],
        cons: ['Может выдумывать факты', 'Бесплатный тариф имеет ограничения', 'Требуется Plus для GPT-4o', 'Нет интернета в реальном времени на бесплатном тарифе'],
        usageInstructions: 'Посетите chat.openai.com и зарегистрируйтесь бесплатно. Введите запрос в поле сообщения. Используйте пользовательские инструкции для сохранения предпочтений. Обновитесь до Plus для доступа к GPT-4o.',
      },
    },
    categories: ['text-generation', 'chatbots'],
  },
  {
    name: 'Claude',
    slug: 'claude',
    logo: gf('claude.ai'),
    websiteUrl: 'https://claude.ai',
    description: 'Claude is an AI assistant by Anthropic known for nuanced understanding, strong reasoning, and a 200K token context window. Excellent for analyzing long documents and complex tasks.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['200K token context window', 'Excellent at long documents', 'Strong reasoning', 'Follows complex instructions', 'Safety-focused design'],
    cons: ['No image generation', 'Limited free tier messages', 'No built-in web search'],
    alternatives: ['chatgpt', 'gemini', 'perplexity'],
    usageInstructions: 'Visit claude.ai and create a free account. Paste long documents directly into the chat. Claude excels at analysis, writing, and coding. Use Projects to maintain persistent context.',
    featured: true,
    translations: {
      ru: {
        description: 'Claude — ИИ-ассистент от Anthropic, известный глубоким пониманием, сильным рассуждением и контекстным окном в 200K токенов. Отлично подходит для анализа длинных документов и сложных задач.',
        pros: ['Контекстное окно 200K токенов', 'Отлично работает с длинными документами', 'Сильное логическое мышление', 'Следует сложным инструкциям', 'Проектирование с акцентом на безопасность'],
        cons: ['Нет генерации изображений', 'Ограниченное количество сообщений на бесплатном тарифе', 'Нет встроенного веб-поиска'],
        usageInstructions: 'Посетите claude.ai и создайте бесплатный аккаунт. Вставляйте длинные документы прямо в чат. Claude отлично справляется с анализом, написанием текстов и программированием. Используйте Проекты для сохранения контекста.',
      },
    },
    categories: ['text-generation', 'chatbots'],
  },
  {
    name: 'Gemini',
    slug: 'gemini',
    logo: gf('gemini.google.com'),
    websiteUrl: 'https://gemini.google.com',
    description: 'Google Gemini is a multimodal AI model that understands text, images, audio, and code. Features real-time Google Search integration and connects with Google Workspace.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Real-time Google Search', 'Google Workspace integration', 'Multimodal (text, image, audio)', 'Free to use', 'Long context window'],
    cons: ['Sometimes less accurate than competitors', 'Privacy concerns', 'Limited API free tier'],
    alternatives: ['chatgpt', 'claude', 'perplexity'],
    usageInstructions: 'Go to gemini.google.com and sign in with your Google account. You can upload images, ask questions with live search results, and connect to Gmail and Docs.',
    featured: true,
    translations: {
      ru: {
        description: 'Google Gemini — мультимодальная ИИ-модель, понимающая текст, изображения, аудио и код. Поддерживает интеграцию с Google Поиском в реальном времени и Google Workspace.',
        pros: ['Поиск Google в реальном времени', 'Интеграция с Google Workspace', 'Мультимодальность (текст, изображения, аудио)', 'Бесплатное использование', 'Большое контекстное окно'],
        cons: ['Иногда менее точен чем конкуренты', 'Проблемы конфиденциальности', 'Ограниченный бесплатный уровень API'],
        usageInstructions: 'Перейдите на gemini.google.com и войдите с аккаунтом Google. Можно загружать изображения, задавать вопросы с актуальными результатами поиска и подключаться к Gmail и Docs.',
      },
    },
    categories: ['text-generation', 'chatbots'],
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity',
    logo: gf('perplexity.ai'),
    websiteUrl: 'https://perplexity.ai',
    description: 'Perplexity AI is an AI-powered search engine that provides accurate, up-to-date answers with cited sources, combining large language models with real-time web search.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Real-time web search', 'Cited sources for every answer', 'Always up-to-date', 'Great for research', 'Multiple search modes'],
    cons: ['Less creative than pure LLMs', 'Pro needed for advanced models', 'Limited document upload'],
    alternatives: ['chatgpt', 'gemini', 'you-com'],
    usageInstructions: 'Visit perplexity.ai and type your question. Switch between Web, Academic, YouTube, and Reddit modes. All answers include sources you can verify.',
    featured: true,
    translations: {
      ru: {
        description: 'Perplexity AI — поисковый движок на основе ИИ, дающий точные и актуальные ответы с цитируемыми источниками, объединяя языковые модели с веб-поиском в реальном времени.',
        pros: ['Веб-поиск в реальном времени', 'Цитируемые источники для каждого ответа', 'Всегда актуальные данные', 'Отлично подходит для исследований', 'Несколько режимов поиска'],
        cons: ['Менее творческий, чем чистые языковые модели', 'Нужен Pro для продвинутых моделей', 'Ограниченная загрузка документов'],
        usageInstructions: 'Перейдите на perplexity.ai и введите свой вопрос. Переключайтесь между режимами Web, Academic, YouTube и Reddit. Все ответы содержат источники для проверки.',
      },
    },
    categories: ['text-generation', 'chatbots'],
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    logo: gf('midjourney.com'),
    websiteUrl: 'https://midjourney.com',
    description: 'Midjourney creates stunning, artistic AI-generated images from text prompts. Renowned for exceptional aesthetic quality and unique visual style loved by designers and artists.',
    pricingType: 'PAID' as PricingType,
    pros: ['Exceptional artistic quality', 'Unique aesthetic style', 'Active community', 'Regular model updates', 'Style consistency'],
    cons: ['No free tier', 'Discord-based interface', 'No public API', 'Limited fine control'],
    alternatives: ['dall-e-3', 'stable-diffusion', 'adobe-firefly'],
    usageInstructions: 'Join the Midjourney Discord. Use /imagine followed by your prompt. Adjust with --ar for aspect ratio, --v for version, --style for aesthetic. Upscale your favorites.',
    featured: true,
    translations: {
      ru: {
        description: 'Midjourney создаёт потрясающие художественные изображения по текстовым описаниям. Известен исключительным эстетическим качеством и уникальным визуальным стилем, любимым дизайнерами и художниками.',
        pros: ['Исключительное художественное качество', 'Уникальный эстетический стиль', 'Активное сообщество', 'Регулярные обновления модели', 'Стилевая консистентность'],
        cons: ['Нет бесплатного тарифа', 'Интерфейс через Discord', 'Нет публичного API', 'Ограниченный тонкий контроль'],
        usageInstructions: 'Присоединитесь к Discord Midjourney. Используйте /imagine с вашим запросом. Настраивайте через --ar для соотношения сторон, --v для версии, --style для стиля. Улучшайте понравившиеся.',
      },
    },
    categories: ['image-generation'],
  },
  {
    name: 'DALL-E 3',
    slug: 'dall-e-3',
    logo: gf('openai.com'),
    websiteUrl: 'https://openai.com/dall-e-3',
    description: "DALL-E 3 is OpenAI's advanced image generation model with remarkable accuracy to text prompts. Integrated directly into ChatGPT for easy use with prompt refinement assistance.",
    pricingType: 'PAID' as PricingType,
    pros: ['High accuracy to prompts', 'ChatGPT integration', 'Good text rendering', 'API available', 'Safety features built-in'],
    cons: ['Requires ChatGPT Plus or API credits', 'Conservative content policy', 'Less artistic than Midjourney'],
    alternatives: ['midjourney', 'stable-diffusion', 'adobe-firefly'],
    usageInstructions: 'Access DALL-E 3 via ChatGPT Plus by asking it to generate an image. Or use the OpenAI API. Describe your image in detail for best results.',
    featured: false,
    translations: {
      ru: {
        description: 'DALL-E 3 — продвинутая модель генерации изображений от OpenAI с высокой точностью следования текстовым запросам. Интегрирован в ChatGPT для удобного использования.',
        pros: ['Высокая точность следования запросам', 'Интеграция с ChatGPT', 'Хорошая передача текста', 'Доступен API', 'Встроенные средства безопасности'],
        cons: ['Требуется ChatGPT Plus или кредиты API', 'Консервативная политика контента', 'Менее художественный чем Midjourney'],
        usageInstructions: 'Получите доступ к DALL-E 3 через ChatGPT Plus, попросив сгенерировать изображение. Или используйте OpenAI API. Подробно описывайте изображение для лучших результатов.',
      },
    },
    categories: ['image-generation'],
  },
  {
    name: 'Stable Diffusion',
    slug: 'stable-diffusion',
    logo: gf('stability.ai'),
    websiteUrl: 'https://stability.ai',
    description: 'Stable Diffusion is an open-source AI image generation model that can run locally on your hardware. Offers unparalleled customization through LoRAs, fine-tuned models, and community workflows.',
    pricingType: 'FREE' as PricingType,
    pros: ['Open source and free', 'Runs locally', 'Highly customizable', 'Thousands of community models', 'No content restrictions (local)'],
    cons: ['Requires technical setup', 'Needs good GPU', 'Quality varies by model', 'Complex for beginners'],
    alternatives: ['midjourney', 'dall-e-3', 'flux'],
    usageInstructions: 'Install AUTOMATIC1111 or ComfyUI. Download a model from Civitai or HuggingFace. Enter your prompt and negative prompt, set steps/CFG scale, and generate.',
    featured: false,
    translations: {
      ru: {
        description: 'Stable Diffusion — модель генерации изображений с открытым исходным кодом, работающая локально на вашем оборудовании. Предлагает беспрецедентные возможности настройки через LoRA и тысячи моделей сообщества.',
        pros: ['Открытый исходный код, бесплатно', 'Работает локально', 'Высокая настраиваемость', 'Тысячи моделей сообщества', 'Нет ограничений контента (локально)'],
        cons: ['Требует технической настройки', 'Нужна хорошая видеокарта', 'Качество зависит от модели', 'Сложно для начинающих'],
        usageInstructions: 'Установите AUTOMATIC1111 или ComfyUI. Скачайте модель с Civitai или HuggingFace. Введите позитивный и негативный промпт, задайте шаги/CFG scale и генерируйте.',
      },
    },
    categories: ['image-generation'],
  },
  {
    name: 'Flux',
    slug: 'flux',
    logo: gf('blackforestlabs.ai'),
    websiteUrl: 'https://blackforestlabs.ai',
    description: 'Flux by Black Forest Labs is a state-of-the-art image generation model with exceptional photorealism and prompt adherence. Available in multiple variants including free open-source versions.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Excellent photorealism', 'Strong prompt adherence', 'Open source variants', 'Multiple model sizes', 'Fast generation'],
    cons: ['Some variants require payment', 'NSFW restrictions on hosted platforms', 'Less artistic than Midjourney'],
    alternatives: ['midjourney', 'stable-diffusion', 'leonardo-ai'],
    usageInstructions: 'Access Flux through fal.ai, Replicate, or ComfyUI locally. Flux.1 Schnell is free. Use detailed prompts for best photorealistic results.',
    featured: false,
    translations: {
      ru: {
        description: 'Flux от Black Forest Labs — современная модель генерации изображений с превосходным фотореализмом и точным следованием запросам. Доступна в нескольких вариантах, включая бесплатные open-source версии.',
        pros: ['Отличный фотореализм', 'Точное следование запросам', 'Open-source варианты', 'Несколько размеров моделей', 'Быстрая генерация'],
        cons: ['Некоторые варианты платные', 'NSFW ограничения на хостинговых платформах', 'Менее художественный чем Midjourney'],
        usageInstructions: 'Используйте Flux через fal.ai, Replicate или ComfyUI локально. Flux.1 Schnell — бесплатный. Используйте детальные запросы для наилучших фотореалистичных результатов.',
      },
    },
    categories: ['image-generation'],
  },
  {
    name: 'Runway',
    slug: 'runway',
    logo: gf('runwayml.com'),
    websiteUrl: 'https://runwayml.com',
    description: 'Runway is a leading AI video generation and editing platform used by professional filmmakers and content creators. Features Gen-3 Alpha for text-to-video and powerful editing tools.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['High quality video generation', 'Professional editing suite', 'Motion brush control', 'Regular model improvements', 'Text and image to video'],
    cons: ['Expensive for heavy use', 'Limited free credits', 'Generation can be slow', 'Watermark on free tier'],
    alternatives: ['pika', 'sora', 'kling'],
    usageInstructions: 'Sign up at runwayml.com. Use Gen-3 Alpha for text-to-video. Upload a reference image for image-to-video. Use Motion Brush to control movement.',
    featured: false,
    translations: {
      ru: {
        description: 'Runway — ведущая платформа генерации и редактирования ИИ-видео, используемая профессиональными кинематографистами. Включает Gen-3 Alpha для перевода текста в видео и мощные инструменты редактирования.',
        pros: ['Высококачественная генерация видео', 'Профессиональный набор редактирования', 'Управление через Motion Brush', 'Регулярные улучшения модели', 'Текст и изображение в видео'],
        cons: ['Дорого при интенсивном использовании', 'Ограниченные бесплатные кредиты', 'Генерация может быть медленной', 'Водяной знак на бесплатном тарифе'],
        usageInstructions: 'Зарегистрируйтесь на runwayml.com. Используйте Gen-3 Alpha для генерации видео из текста. Загрузите изображение для преобразования в видео. Используйте Motion Brush для управления движением.',
      },
    },
    categories: ['video-generation'],
  },
  {
    name: 'Pika',
    slug: 'pika',
    logo: gf('pika.art'),
    websiteUrl: 'https://pika.art',
    description: 'Pika is an AI video generation platform making video creation accessible for social media content creators. Features easy text-to-video with style controls.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Easy to use interface', 'Good for social content', 'Video modification feature', 'Regular updates', 'Free tier available'],
    cons: ['Limited video length', 'Less control than Runway', 'Occasional quality issues'],
    alternatives: ['runway', 'kling', 'sora'],
    usageInstructions: 'Visit pika.art and create an account. Enter a text prompt to generate a video. Use the Modify feature to adjust existing clips. Control style with keywords.',
    featured: false,
    translations: {
      ru: {
        description: 'Pika — платформа генерации видео с ИИ, делающая создание видео доступным для авторов контента в социальных сетях. Поддерживает простой перевод текста в видео с управлением стилем.',
        pros: ['Простой интерфейс', 'Хорошо подходит для социального контента', 'Функция изменения видео', 'Регулярные обновления', 'Доступен бесплатный тариф'],
        cons: ['Ограниченная длина видео', 'Меньше контроля чем в Runway', 'Периодические проблемы с качеством'],
        usageInstructions: 'Посетите pika.art и создайте аккаунт. Введите текстовый запрос для генерации видео. Используйте функцию Modify для изменения существующих клипов. Управляйте стилем с помощью ключевых слов.',
      },
    },
    categories: ['video-generation'],
  },
  {
    name: 'Sora',
    slug: 'sora',
    logo: gf('sora.com'),
    websiteUrl: 'https://sora.com',
    description: "Sora is OpenAI's advanced text-to-video model capable of generating realistic and imaginative scenes up to 60 seconds long with impressive physical simulation and consistency.",
    pricingType: 'PAID' as PricingType,
    pros: ['Highly realistic videos', 'Long video support (60s)', 'Complex scene understanding', 'High resolution output', 'Remix existing videos'],
    cons: ['Requires ChatGPT Plus or Pro', 'Expensive', 'Long generation times', 'Limited availability'],
    alternatives: ['runway', 'pika', 'kling'],
    usageInstructions: 'Access Sora at sora.com with a ChatGPT Plus or Pro subscription. Write a detailed prompt. Use Storyboard mode for multi-scene videos. Remix to modify existing generations.',
    featured: false,
    translations: {
      ru: {
        description: 'Sora — продвинутая модель OpenAI для преобразования текста в видео, способная генерировать реалистичные сцены длительностью до 60 секунд с впечатляющей физической симуляцией.',
        pros: ['Высокореалистичные видео', 'Поддержка длинных видео (60 сек)', 'Понимание сложных сцен', 'Вывод в высоком разрешении', 'Ремикс существующих видео'],
        cons: ['Требуется ChatGPT Plus или Pro', 'Дорого', 'Долгое время генерации', 'Ограниченная доступность'],
        usageInstructions: 'Откройте Sora на sora.com с подпиской ChatGPT Plus или Pro. Напишите детальный запрос. Используйте режим Storyboard для многосценных видео. Ремикс для изменения существующих генераций.',
      },
    },
    categories: ['video-generation'],
  },
  {
    name: 'Kling AI',
    slug: 'kling',
    logo: gf('klingai.com'),
    websiteUrl: 'https://klingai.com',
    description: 'Kling is an AI video generation model by Kuaishou with impressive physical simulation and realistic motion. Creates high-quality videos from text or images.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Excellent video quality', 'Realistic physics simulation', 'Image-to-video capability', 'Free credits available', 'Long video generation'],
    cons: ['Slower generation times', 'Credit-based system', 'UI primarily in Chinese'],
    alternatives: ['runway', 'pika', 'sora'],
    usageInstructions: 'Visit klingai.com and create an account. Enter your text prompt or upload an image. Select duration (5 or 10 seconds) and aspect ratio. Generate and download.',
    featured: false,
    translations: {
      ru: {
        description: 'Kling — модель генерации видео от Kuaishou с впечатляющей физической симуляцией и реалистичным движением. Создаёт высококачественные видео из текста или изображений.',
        pros: ['Отличное качество видео', 'Реалистичная физическая симуляция', 'Преобразование изображения в видео', 'Доступны бесплатные кредиты', 'Генерация длинных видео'],
        cons: ['Медленное время генерации', 'Система кредитов', 'Интерфейс преимущественно на китайском'],
        usageInstructions: 'Посетите klingai.com и создайте аккаунт. Введите текстовый запрос или загрузите изображение. Выберите длительность (5 или 10 секунд) и соотношение сторон. Генерируйте и скачивайте.',
      },
    },
    categories: ['video-generation'],
  },
  {
    name: 'Suno',
    slug: 'suno',
    logo: gf('suno.ai'),
    websiteUrl: 'https://suno.ai',
    description: 'Suno creates complete songs with vocals, melody, and instrumentation from text prompts. One of the best AI music generators supporting virtually any genre.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Creates full songs with vocals', 'Wide genre support', 'High quality audio', 'Daily free credits', 'Custom lyrics mode'],
    cons: ['Copyright considerations', 'Limited fine-grained control', 'Commercial use needs paid plan'],
    alternatives: ['udio', 'musicgen'],
    usageInstructions: 'Visit suno.ai and sign in. Describe your song including style and mood. Use Custom Mode to provide your own lyrics. Download and use in your projects.',
    featured: false,
    translations: {
      ru: {
        description: 'Suno создаёт полноценные песни с вокалом, мелодией и инструментальным сопровождением из текстовых запросов. Один из лучших ИИ-генераторов музыки с поддержкой практически любого жанра.',
        pros: ['Создаёт полные песни с вокалом', 'Широкая поддержка жанров', 'Высокое качество аудио', 'Ежедневные бесплатные кредиты', 'Режим пользовательских текстов'],
        cons: ['Вопросы авторского права', 'Ограниченный тонкий контроль', 'Коммерческое использование требует платного плана'],
        usageInstructions: 'Посетите suno.ai и войдите в систему. Опишите вашу песню, включая стиль и настроение. Используйте Custom Mode для предоставления собственных текстов. Скачайте и используйте в проектах.',
      },
    },
    categories: ['music-generation'],
  },
  {
    name: 'Udio',
    slug: 'udio',
    logo: gf('udio.com'),
    websiteUrl: 'https://udio.com',
    description: 'Udio generates high-quality music from text prompts with detailed style control. Known for professional audio quality and the ability to create extended tracks.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Professional audio quality', 'Detailed style control', 'Extend tracks feature', 'Stems and remixing', 'Free tier available'],
    cons: ['Slower than some competitors', 'Learning curve for best results', 'Credit-based system'],
    alternatives: ['suno', 'musicgen'],
    usageInstructions: 'Create an account at udio.com. Enter detailed prompts including genre, mood, tempo, and instruments. Use the Extend feature to add more to your track.',
    featured: false,
    translations: {
      ru: {
        description: 'Udio генерирует высококачественную музыку из текстовых запросов с детальным контролем стиля. Известен профессиональным качеством аудио и возможностью создавать расширенные треки.',
        pros: ['Профессиональное качество аудио', 'Детальный контроль стиля', 'Функция расширения треков', 'Стемы и ремиксирование', 'Доступен бесплатный тариф'],
        cons: ['Медленнее некоторых конкурентов', 'Кривая обучения для лучших результатов', 'Система кредитов'],
        usageInstructions: 'Создайте аккаунт на udio.com. Вводите детальные запросы с указанием жанра, настроения, темпа и инструментов. Используйте функцию Extend для дополнения треков.',
      },
    },
    categories: ['music-generation'],
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    logo: gf('elevenlabs.io'),
    websiteUrl: 'https://elevenlabs.io',
    description: 'ElevenLabs is the leading AI voice synthesis platform offering incredibly realistic text-to-speech, instant voice cloning, and dubbing in 29+ languages.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Industry-leading voice realism', 'Voice cloning in minutes', '29+ language support', 'Full API access', 'Large voice library'],
    cons: ['Expensive for high volume', 'Free tier has strict limits', 'Voice cloning ethics'],
    alternatives: ['play-ht', 'murf', 'azure-speech'],
    usageInstructions: 'Sign up at elevenlabs.io. Select a voice or clone your own by uploading a sample. Enter text and click Generate. Adjust stability and similarity sliders.',
    featured: false,
    translations: {
      ru: {
        description: 'ElevenLabs — ведущая платформа ИИ-синтеза голоса с невероятно реалистичным озвучиванием текста, мгновенным клонированием голоса и дублированием на 29+ языках.',
        pros: ['Лидирующий реализм голоса в отрасли', 'Клонирование голоса за минуты', 'Поддержка 29+ языков', 'Полный доступ к API', 'Большая библиотека голосов'],
        cons: ['Дорого при большом объёме', 'Строгие лимиты бесплатного тарифа', 'Этические вопросы клонирования голоса'],
        usageInstructions: 'Зарегистрируйтесь на elevenlabs.io. Выберите голос или клонируйте свой, загрузив образец. Введите текст и нажмите Generate. Настройте ползунки stability и similarity.',
      },
    },
    categories: ['voice-speech'],
  },
  {
    name: 'Play.ht',
    slug: 'play-ht',
    logo: gf('play.ht'),
    websiteUrl: 'https://play.ht',
    description: 'Play.ht offers over 900 AI voices in 142 languages for text-to-speech generation with real-time streaming, voice cloning, and a WordPress plugin.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['900+ voices available', '142 language support', 'Real-time streaming API', 'WordPress plugin', 'Voice cloning'],
    cons: ['Quality varies between voices', 'Complex pricing', 'UI can be confusing'],
    alternatives: ['elevenlabs', 'murf', 'amazon-polly'],
    usageInstructions: 'Visit play.ht and create an account. Paste your text in the editor, choose a voice and language, then generate. Use the API for programmatic access.',
    featured: false,
    translations: {
      ru: {
        description: 'Play.ht предлагает более 900 ИИ-голосов на 142 языках для генерации текста в речь с потоковой передачей в реальном времени, клонированием голоса и плагином для WordPress.',
        pros: ['Более 900 голосов', 'Поддержка 142 языков', 'API потоковой передачи в реальном времени', 'Плагин для WordPress', 'Клонирование голоса'],
        cons: ['Качество варьируется между голосами', 'Сложное ценообразование', 'Интерфейс может сбивать с толку'],
        usageInstructions: 'Посетите play.ht и создайте аккаунт. Вставьте текст в редактор, выберите голос и язык, затем сгенерируйте. Используйте API для программного доступа.',
      },
    },
    categories: ['voice-speech'],
  },
  {
    name: 'Whisper',
    slug: 'whisper',
    logo: gf('openai.com'),
    websiteUrl: 'https://openai.com/research/whisper',
    description: "OpenAI's Whisper is an open-source automatic speech recognition system achieving human-level accuracy across multiple languages, accents, and audio quality levels.",
    pricingType: 'FREE' as PricingType,
    pros: ['Open source and free', 'Near-human accuracy', 'Supports 99 languages', 'Runs locally', 'Robust to noise'],
    cons: ['Requires technical setup locally', 'Not real-time by default', 'Large model size'],
    alternatives: ['assemblyai', 'deepgram', 'azure-speech'],
    usageInstructions: 'Install via pip: `pip install openai-whisper`. Run `whisper audio.mp3 --model base`. Or use the OpenAI API endpoint at $0.006/min.',
    featured: false,
    translations: {
      ru: {
        description: 'Whisper от OpenAI — система распознавания речи с открытым исходным кодом, достигающая человеческой точности для нескольких языков, акцентов и уровней качества аудио.',
        pros: ['Открытый исходный код, бесплатно', 'Точность близкая к человеческой', 'Поддерживает 99 языков', 'Работает локально', 'Устойчив к шумам'],
        cons: ['Требует технической настройки локально', 'По умолчанию не работает в реальном времени', 'Большой размер модели'],
        usageInstructions: 'Установите через pip: `pip install openai-whisper`. Запустите `whisper audio.mp3 --model base`. Или используйте конечную точку OpenAI API за $0.006/мин.',
      },
    },
    categories: ['voice-speech'],
  },
  {
    name: 'DeepL',
    slug: 'deepl',
    logo: gf('deepl.com'),
    websiteUrl: 'https://deepl.com',
    description: 'DeepL Translator produces strikingly natural translations using neural networks. Consistently outperforms competitors for European languages and is trusted by professional translators.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Most natural-sounding translations', 'Document translation (PDF, Word)', 'Glossary feature', 'API available', 'Generous free tier'],
    cons: ['Supports fewer languages than Google', 'Document conversion limits', 'API costs scale with volume'],
    alternatives: ['google-translate', 'microsoft-translator'],
    usageInstructions: 'Go to deepl.com and paste text or upload a document. Select source and target languages. DeepL auto-detects the source language. Use DeepL Write for text improvement.',
    featured: false,
    translations: {
      ru: {
        description: 'Переводчик DeepL создаёт поразительно естественные переводы с использованием нейронных сетей. Стабильно превосходит конкурентов для европейских языков и пользуется доверием профессиональных переводчиков.',
        pros: ['Самые естественные переводы', 'Перевод документов (PDF, Word)', 'Функция глоссария', 'Доступен API', 'Щедрый бесплатный тариф'],
        cons: ['Поддерживает меньше языков чем Google', 'Ограничения конвертации документов', 'Стоимость API растёт с объёмом'],
        usageInstructions: 'Перейдите на deepl.com и вставьте текст или загрузите документ. Выберите исходный и целевой языки. DeepL автоматически определяет исходный язык. Используйте DeepL Write для улучшения текста.',
      },
    },
    categories: ['translation'],
  },
  {
    name: 'Google Translate',
    slug: 'google-translate',
    logo: gf('translate.google.com'),
    websiteUrl: 'https://translate.google.com',
    description: 'Google Translate is a free multilingual translation service supporting 133 languages. Features text, document, image, and real-time conversation translation.',
    pricingType: 'FREE' as PricingType,
    pros: ['Completely free', '133 languages supported', 'Camera/image translation', 'Offline mode', 'Conversation mode'],
    cons: ['Less natural than DeepL', 'Awkward phrasing for complex sentences', 'Google privacy concerns'],
    alternatives: ['deepl', 'microsoft-translator'],
    usageInstructions: 'Go to translate.google.com or use the mobile app. Type, paste, speak, or photograph text. Camera mode translates signs instantly. Download languages for offline use.',
    featured: false,
    translations: {
      ru: {
        description: 'Google Переводчик — бесплатный многоязычный сервис перевода с поддержкой 133 языков. Поддерживает перевод текста, документов, изображений и разговоров в реальном времени.',
        pros: ['Полностью бесплатно', 'Поддерживается 133 языка', 'Перевод через камеру/изображение', 'Офлайн-режим', 'Режим разговора'],
        cons: ['Менее естественный чем DeepL', 'Неловкие формулировки сложных предложений', 'Вопросы конфиденциальности Google'],
        usageInstructions: 'Перейдите на translate.google.com или используйте мобильное приложение. Вводите, вставляйте, произносите или фотографируйте текст. Режим камеры мгновенно переводит вывески. Скачайте языки для офлайн-использования.',
      },
    },
    categories: ['translation'],
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    logo: gf('cursor.sh'),
    websiteUrl: 'https://cursor.sh',
    description: 'Cursor is an AI-first code editor built on VS Code with deep AI integration for code completion, natural language editing, and codebase-aware chat. The go-to tool for AI-assisted development.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Best-in-class AI code completion', 'Natural language code editing', 'Full VS Code compatibility', 'Codebase understanding', 'Multi-model support'],
    cons: ['Paid plan for advanced use', 'Code privacy concerns', 'Learning curve for AI features'],
    alternatives: ['github-copilot', 'codeium', 'windsurf'],
    usageInstructions: 'Download from cursor.sh. Use Ctrl+K for inline AI edits, Ctrl+L for AI chat, Tab for completions. Add @codebase for full-project context. Switch models as needed.',
    featured: true,
    translations: {
      ru: {
        description: 'Cursor — ИИ-редактор кода на основе VS Code с глубокой интеграцией ИИ для автодополнения кода, редактирования на естественном языке и чата с пониманием кодовой базы.',
        pros: ['Лучшее в классе автодополнение кода', 'Редактирование кода на естественном языке', 'Полная совместимость с VS Code', 'Понимание кодовой базы', 'Поддержка нескольких моделей'],
        cons: ['Платный план для продвинутого использования', 'Вопросы конфиденциальности кода', 'Кривая обучения для функций ИИ'],
        usageInstructions: 'Скачайте с cursor.sh. Используйте Ctrl+K для встроенного редактирования ИИ, Ctrl+L для чата с ИИ, Tab для автодополнений. Добавьте @codebase для контекста всего проекта. Переключайте модели по необходимости.',
      },
    },
    categories: ['programming'],
  },
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    logo: gf('github.com'),
    websiteUrl: 'https://github.com/features/copilot',
    description: 'GitHub Copilot is an AI pair programmer offering code completions, chat, and PR summaries. Powers development across VS Code, JetBrains, Neovim, and more IDEs.',
    pricingType: 'PAID' as PricingType,
    pros: ['Deep IDE integration', 'GitHub ecosystem', 'Copilot Chat', 'PR summaries', 'CLI support'],
    cons: ['No free tier (except students)', 'Monthly subscription', 'Privacy concerns', 'Can suggest buggy code'],
    alternatives: ['cursor', 'codeium', 'tabnine'],
    usageInstructions: 'Install the Copilot extension in VS Code. Sign in with your GitHub account. Accept suggestions with Tab. Use Copilot Chat (Ctrl+Shift+I) for conversations.',
    featured: false,
    translations: {
      ru: {
        description: 'GitHub Copilot — ИИ-напарник по программированию с автодополнением кода, чатом и резюме PR. Поддерживает разработку в VS Code, JetBrains, Neovim и других IDE.',
        pros: ['Глубокая интеграция с IDE', 'Экосистема GitHub', 'Copilot Chat', 'Резюме PR', 'Поддержка CLI'],
        cons: ['Нет бесплатного тарифа (кроме студентов)', 'Ежемесячная подписка', 'Вопросы конфиденциальности', 'Может предлагать некорректный код'],
        usageInstructions: 'Установите расширение Copilot в VS Code. Войдите с аккаунтом GitHub. Принимайте подсказки клавишей Tab. Используйте Copilot Chat (Ctrl+Shift+I) для разговоров.',
      },
    },
    categories: ['programming'],
  },
  {
    name: 'Codeium',
    slug: 'codeium',
    logo: gf('codeium.com'),
    websiteUrl: 'https://codeium.com',
    description: 'Codeium is a free AI coding assistant supporting 70+ programming languages with code completions, search, and chat. A solid free alternative to GitHub Copilot.',
    pricingType: 'FREE' as PricingType,
    pros: ['Completely free for individuals', '70+ languages', 'Fast completions', 'All major IDEs supported', 'Privacy-conscious'],
    cons: ['Less powerful than premium tools', 'Limited team features', 'Smaller context window'],
    alternatives: ['cursor', 'github-copilot', 'tabnine'],
    usageInstructions: 'Install the Codeium extension from your IDE marketplace. Create a free account at codeium.com. Start coding and receive inline suggestions automatically.',
    featured: false,
    translations: {
      ru: {
        description: 'Codeium — бесплатный ИИ-ассистент для программирования с поддержкой 70+ языков программирования. Достойная бесплатная альтернатива GitHub Copilot.',
        pros: ['Полностью бесплатно для частных лиц', '70+ языков', 'Быстрые автодополнения', 'Поддерживаются все основные IDE', 'Ориентированность на конфиденциальность'],
        cons: ['Менее мощный чем премиум инструменты', 'Ограниченные командные функции', 'Меньшее контекстное окно'],
        usageInstructions: 'Установите расширение Codeium из маркетплейса вашей IDE. Создайте бесплатный аккаунт на codeium.com. Начните программировать и получайте встроенные подсказки автоматически.',
      },
    },
    categories: ['programming'],
  },
  {
    name: 'Gamma',
    slug: 'gamma',
    logo: gf('gamma.app'),
    websiteUrl: 'https://gamma.app',
    description: 'Gamma creates beautiful presentations, documents, and webpages from a simple prompt or outline in seconds. Modern design, easy editing, and one-click web publishing.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Instant beautiful presentations', 'Multiple export formats', 'Inline editing', 'Template library', 'Web publishing'],
    cons: ['Watermark on free tier', 'Limited design customization', 'Can look similar across users'],
    alternatives: ['tome', 'beautiful-ai', 'canva'],
    usageInstructions: 'Go to gamma.app and click "Create new." Enter a topic or paste an outline. AI generates a complete presentation. Edit text, swap layouts, and publish or export.',
    featured: false,
    translations: {
      ru: {
        description: 'Gamma создаёт красивые презентации, документы и веб-страницы из простого запроса или структуры за секунды. Современный дизайн, лёгкое редактирование и публикация одним кликом.',
        pros: ['Мгновенные красивые презентации', 'Несколько форматов экспорта', 'Встроенное редактирование', 'Библиотека шаблонов', 'Публикация в интернете'],
        cons: ['Водяной знак на бесплатном тарифе', 'Ограниченная настройка дизайна', 'Похожий вид у разных пользователей'],
        usageInstructions: 'Перейдите на gamma.app и нажмите «Создать новое». Введите тему или вставьте структуру. ИИ генерирует полную презентацию. Редактируйте текст, меняйте макеты, публикуйте или экспортируйте.',
      },
    },
    categories: ['presentation-creation'],
  },
  {
    name: 'Tome',
    slug: 'tome',
    logo: gf('tome.app'),
    websiteUrl: 'https://tome.app',
    description: 'Tome is an AI storytelling tool that creates compelling narrative presentations. Blends text, images, and AI-generated content into beautiful, story-driven formats.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Beautiful narrative design', 'AI content generation', 'Easy collaboration', 'Responsive on mobile', 'Live embeds'],
    cons: ['Less PowerPoint-like features', 'Can be slow to load', 'Limited free pages'],
    alternatives: ['gamma', 'beautiful-ai', 'pitch'],
    usageInstructions: 'Visit tome.app and sign in. Click "Create" and describe your presentation. Use AI prompts for each page. Add images, videos, and live embeds to enrich content.',
    featured: false,
    translations: {
      ru: {
        description: 'Tome — ИИ-инструмент для создания повествовательных презентаций. Объединяет текст, изображения и ИИ-контент в красивые форматы, ориентированные на рассказ историй.',
        pros: ['Красивый нарративный дизайн', 'Генерация контента ИИ', 'Лёгкое сотрудничество', 'Адаптивность на мобильных', 'Живые встраивания'],
        cons: ['Меньше функций как в PowerPoint', 'Может медленно загружаться', 'Ограниченное число бесплатных страниц'],
        usageInstructions: 'Посетите tome.app и войдите. Нажмите «Create» и опишите свою презентацию. Используйте ИИ-запросы для каждой страницы. Добавляйте изображения, видео и живые встраивания для обогащения контента.',
      },
    },
    categories: ['presentation-creation'],
  },
  {
    name: 'Beautiful.ai',
    slug: 'beautiful-ai',
    logo: gf('beautiful.ai'),
    websiteUrl: 'https://beautiful.ai',
    description: 'Beautiful.ai automatically designs your slides as you add content using smart layouts and design templates, ensuring professional presentations without design skills.',
    pricingType: 'PAID' as PricingType,
    pros: ['Auto-adjusting smart layouts', 'Brand kit support', 'Team collaboration', 'Large template library', 'Professional look always'],
    cons: ['No free tier', 'Less design flexibility', 'Expensive team plans'],
    alternatives: ['gamma', 'canva', 'pitch'],
    usageInstructions: 'Subscribe at beautiful.ai. Create a presentation from a template or blank. Add content to smart slides that auto-arrange. Set your brand colors and fonts once.',
    featured: false,
    translations: {
      ru: {
        description: 'Beautiful.ai автоматически оформляет слайды по мере добавления контента с умными макетами и шаблонами дизайна, обеспечивая профессиональный вид без навыков дизайна.',
        pros: ['Автоматически настраиваемые умные макеты', 'Поддержка брендбука', 'Командная совместная работа', 'Большая библиотека шаблонов', 'Всегда профессиональный вид'],
        cons: ['Нет бесплатного тарифа', 'Меньше гибкости дизайна', 'Дорогие командные планы'],
        usageInstructions: 'Подпишитесь на beautiful.ai. Создайте презентацию из шаблона или с нуля. Добавляйте контент в умные слайды, которые автоматически выстраиваются. Задайте цвета и шрифты бренда один раз.',
      },
    },
    categories: ['presentation-creation'],
  },
  {
    name: 'Grammarly',
    slug: 'grammarly',
    logo: gf('grammarly.com'),
    websiteUrl: 'https://grammarly.com',
    description: 'Grammarly is an AI writing assistant that checks grammar, spelling, style, clarity, and tone while suggesting improvements across all your apps via browser extension.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Works everywhere via extension', 'Tone detection', 'Style improvements', 'Plagiarism checker (Premium)', 'Clear explanations'],
    cons: ['Full features need Premium', 'Can be overly aggressive', 'Privacy concerns'],
    alternatives: ['hemingway', 'quillbot', 'wordtune'],
    usageInstructions: 'Install the Grammarly browser extension. Write in any online editor and see suggestions highlighted. Click to accept or reject. Use the Grammarly Editor for standalone documents.',
    featured: false,
    translations: {
      ru: {
        description: 'Grammarly — ИИ-помощник по написанию, проверяющий грамматику, орфографию, стиль, ясность и тон, предлагая улучшения во всех приложениях через браузерное расширение.',
        pros: ['Работает везде через расширение', 'Определение тона', 'Улучшение стиля', 'Проверка на плагиат (Premium)', 'Чёткие объяснения'],
        cons: ['Полный функционал требует Premium', 'Может быть излишне навязчивым', 'Вопросы конфиденциальности'],
        usageInstructions: 'Установите браузерное расширение Grammarly. Пишите в любом онлайн-редакторе и видите подсвеченные подсказки. Нажимайте для принятия или отклонения. Используйте редактор Grammarly для отдельных документов.',
      },
    },
    categories: ['text-generation', 'document-processing'],
  },
  {
    name: 'Jasper AI',
    slug: 'jasper',
    logo: gf('jasper.ai'),
    websiteUrl: 'https://jasper.ai',
    description: 'Jasper is an enterprise AI content platform purpose-built for marketing teams. Offers templates for blogs, ads, emails, and social media with brand voice training.',
    pricingType: 'PAID' as PricingType,
    pros: ['Marketing-focused templates', 'Brand voice consistency', 'Team collaboration', 'SEO mode integration', 'Multi-language support'],
    cons: ['No free tier', 'Expensive plans', 'Output can be generic'],
    alternatives: ['copy-ai', 'writesonic', 'chatgpt'],
    usageInstructions: 'Subscribe to Jasper at jasper.ai. Choose a template for your content type. Input your brand, product, and audience details. Train Brand Voice for consistent output.',
    featured: false,
    translations: {
      ru: {
        description: 'Jasper — корпоративная ИИ-платформа для контента, созданная для маркетинговых команд. Предлагает шаблоны для блогов, рекламы, писем и социальных сетей с обучением голосу бренда.',
        pros: ['Шаблоны с фокусом на маркетинг', 'Согласованность голоса бренда', 'Командная совместная работа', 'Интеграция с SEO-режимом', 'Поддержка нескольких языков'],
        cons: ['Нет бесплатного тарифа', 'Дорогие планы', 'Вывод может быть обобщённым'],
        usageInstructions: 'Подпишитесь на Jasper на jasper.ai. Выберите шаблон для вашего типа контента. Введите данные о бренде, продукте и аудитории. Обучите Brand Voice для последовательного вывода.',
      },
    },
    categories: ['text-generation'],
  },
  {
    name: 'Copy.ai',
    slug: 'copy-ai',
    logo: gf('copy.ai'),
    websiteUrl: 'https://copy.ai',
    description: 'Copy.ai is an AI copywriting platform with 90+ templates for marketing copy, blog posts, social media, and product descriptions. Features workflow automation for teams.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['90+ content templates', 'Workflow automation', 'Brand voice feature', 'Chat interface', 'Free tier available'],
    cons: ['Output can be generic', 'Less powerful than ChatGPT', 'Template quality varies'],
    alternatives: ['jasper', 'writesonic', 'chatgpt'],
    usageInstructions: 'Go to copy.ai and sign up. Choose a template like "Blog Post Intro" or use the free-form Chat. Enter your product/topic details. Refine with follow-up prompts.',
    featured: false,
    translations: {
      ru: {
        description: 'Copy.ai — ИИ-платформа для копирайтинга с 90+ шаблонами для маркетинговых текстов, постов в блоге, социальных сетях и описаний продуктов. Включает автоматизацию рабочих процессов для команд.',
        pros: ['90+ шаблонов контента', 'Автоматизация рабочих процессов', 'Функция голоса бренда', 'Чат-интерфейс', 'Доступен бесплатный тариф'],
        cons: ['Вывод может быть обобщённым', 'Менее мощный чем ChatGPT', 'Качество шаблонов варьируется'],
        usageInstructions: 'Перейдите на copy.ai и зарегистрируйтесь. Выберите шаблон, например «Вступление к блог-посту», или используйте свободный Chat. Введите данные о продукте/теме. Уточняйте последующими запросами.',
      },
    },
    categories: ['text-generation'],
  },
  {
    name: 'Adobe Firefly',
    slug: 'adobe-firefly',
    logo: gf('firefly.adobe.com'),
    websiteUrl: 'https://firefly.adobe.com',
    description: "Adobe Firefly is Adobe's generative AI creative suite offering text-to-image, generative fill, text effects, and recoloring — all commercially safe and integrated with Creative Cloud.",
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Commercially safe (licensed training data)', 'Creative Cloud integration', 'Generative Fill in Photoshop', 'High-quality text effects', 'Vector recoloring'],
    cons: ['Full features need Adobe subscription', 'Less artistic than Midjourney', 'Credit-based generation'],
    alternatives: ['midjourney', 'dall-e-3', 'stable-diffusion'],
    usageInstructions: 'Visit firefly.adobe.com. Enter a prompt for text-to-image. In Photoshop, select any area and use Generative Fill. Use Text Effects for stylized typography.',
    featured: false,
    translations: {
      ru: {
        description: 'Adobe Firefly — генеративный ИИ-творческий пакет Adobe с текстом в изображение, генеративным заполнением и текстовыми эффектами. Всё безопасно для коммерческого использования и интегрировано с Creative Cloud.',
        pros: ['Коммерческая безопасность (лицензированные данные)', 'Интеграция с Creative Cloud', 'Генеративное заполнение в Photoshop', 'Высококачественные текстовые эффекты', 'Перекрашивание векторов'],
        cons: ['Полный функционал требует подписки Adobe', 'Менее художественный чем Midjourney', 'Генерация на основе кредитов'],
        usageInstructions: 'Посетите firefly.adobe.com. Введите запрос для генерации изображения. В Photoshop выделите любую область и используйте Generative Fill. Используйте Text Effects для стилизованной типографики.',
      },
    },
    categories: ['image-generation'],
  },
  {
    name: 'Leonardo.ai',
    slug: 'leonardo-ai',
    logo: gf('leonardo.ai'),
    websiteUrl: 'https://leonardo.ai',
    description: 'Leonardo.ai is a powerful AI image generation platform with real-time canvas, game asset creation, and model fine-tuning. Popular with game developers and digital artists.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Real-time generation canvas', 'Game asset specialization', 'Custom model training', 'Daily free tokens', 'Strong community'],
    cons: ['Complex for beginners', 'Daily token limits', 'Inconsistent quality across models'],
    alternatives: ['midjourney', 'stable-diffusion', 'flux'],
    usageInstructions: 'Create an account at leonardo.ai. Go to Image Generation, select a model, enter your prompt, and generate. Use the Real-Time Canvas for instant AI drawing.',
    featured: false,
    translations: {
      ru: {
        description: 'Leonardo.ai — мощная платформа генерации изображений с ИИ с холстом реального времени, созданием игровых ассетов и дообучением моделей. Популярна среди разработчиков игр и цифровых художников.',
        pros: ['Холст генерации в реальном времени', 'Специализация на игровых ассетах', 'Обучение пользовательских моделей', 'Ежедневные бесплатные токены', 'Сильное сообщество'],
        cons: ['Сложно для начинающих', 'Суточные лимиты токенов', 'Непоследовательное качество в разных моделях'],
        usageInstructions: 'Создайте аккаунт на leonardo.ai. Перейдите в Image Generation, выберите модель, введите запрос и генерируйте. Используйте Real-Time Canvas для мгновенного рисования с ИИ.',
      },
    },
    categories: ['image-generation'],
  },
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    logo: gf('notion.so'),
    websiteUrl: 'https://notion.so/product/ai',
    description: 'Notion AI brings AI writing, summarization, translation, and Q&A directly into your Notion workspace. Ask questions about your notes and documents in natural language.',
    pricingType: 'PAID' as PricingType,
    pros: ['Seamless Notion integration', 'Workspace-aware Q&A', 'Document summaries', 'Action item extraction', 'Translation within notes'],
    cons: ['Requires Notion + AI add-on', 'Less powerful than standalone LLMs', 'Extra monthly cost'],
    alternatives: ['chatgpt', 'claude', 'mem-ai'],
    usageInstructions: 'In Notion, press Space for AI or type /AI on any block. Ask AI to write, improve, summarize, translate, or find action items. Use "Ask AI" to search your workspace.',
    featured: false,
    translations: {
      ru: {
        description: 'Notion AI добавляет возможности написания, резюмирования, перевода и ответов на вопросы прямо в рабочее пространство Notion. Задавайте вопросы о своих заметках и документах на естественном языке.',
        pros: ['Бесшовная интеграция с Notion', 'Вопросы и ответы по рабочему пространству', 'Резюме документов', 'Извлечение пунктов действий', 'Перевод в заметках'],
        cons: ['Требует Notion + дополнение ИИ', 'Менее мощный чем отдельные языковые модели', 'Дополнительные ежемесячные расходы'],
        usageInstructions: 'В Notion нажмите пробел для вызова ИИ или введите /AI в любом блоке. Попросите ИИ написать, улучшить, резюмировать, перевести или найти пункты действий. Используйте «Ask AI» для поиска по рабочему пространству.',
      },
    },
    categories: ['document-processing', 'text-generation'],
  },
  {
    name: 'AssemblyAI',
    slug: 'assemblyai',
    logo: gf('assemblyai.com'),
    websiteUrl: 'https://assemblyai.com',
    description: 'AssemblyAI provides an audio AI API with best-in-class speech recognition, speaker diarization, sentiment analysis, topic detection, and LeMUR for audio Q&A.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['High accuracy transcription', 'Speaker diarization', 'LeMUR audio Q&A', 'Sentiment analysis', 'Real-time streaming'],
    cons: ['API-focused (no consumer UI)', 'Costs scale with audio hours', 'Developer knowledge required'],
    alternatives: ['whisper', 'deepgram', 'rev-ai'],
    usageInstructions: 'Sign up at assemblyai.com for an API key. POST your audio URL or file to the API. Poll for results. Use LeMUR to ask questions about transcribed content.',
    featured: false,
    translations: {
      ru: {
        description: 'AssemblyAI предоставляет аудио ИИ API с распознаванием речи, разделением на дикторов, анализом тональности, обнаружением тем и LeMUR для ответов на вопросы по аудио.',
        pros: ['Высокоточная транскрипция', 'Разделение по дикторам', 'LeMUR для вопросов по аудио', 'Анализ тональности', 'Потоковая передача в реальном времени'],
        cons: ['Ориентирован на API (нет потребительского интерфейса)', 'Стоимость растёт с часами аудио', 'Требуются навыки разработчика'],
        usageInstructions: 'Зарегистрируйтесь на assemblyai.com для получения API-ключа. Отправьте POST-запрос с URL аудио или файлом. Опрашивайте результаты. Используйте LeMUR для вопросов по транскрибированному контенту.',
      },
    },
    categories: ['voice-speech', 'document-processing'],
  },
  {
    name: 'Julius AI',
    slug: 'julius-ai',
    logo: gf('julius.ai'),
    websiteUrl: 'https://julius.ai',
    description: 'Julius is an AI data analyst that lets you analyze data, create charts, and run statistical analyses by simply asking questions in plain English about your uploaded CSV or database.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Natural language data analysis', 'Python/R code generation', 'Automated chart creation', 'CSV and Excel upload', 'Statistical analysis'],
    cons: ['Limited free tier queries', 'Large datasets can timeout', 'Less control than coding directly'],
    alternatives: ['chatgpt-code-interpreter', 'databricks', 'rows'],
    usageInstructions: 'Visit julius.ai and upload your CSV or Excel file. Ask questions like "Show me sales trends by month" or "Which product has the highest margin?" Charts generate automatically.',
    featured: false,
    translations: {
      ru: {
        description: 'Julius — ИИ-аналитик данных, позволяющий анализировать данные, создавать диаграммы и проводить статистический анализ, просто задавая вопросы на естественном языке о загруженных данных.',
        pros: ['Анализ данных на естественном языке', 'Генерация кода Python/R', 'Автоматическое создание диаграмм', 'Загрузка CSV и Excel', 'Статистический анализ'],
        cons: ['Ограниченные запросы на бесплатном тарифе', 'Большие датасеты могут зависать', 'Меньше контроля чем при прямом программировании'],
        usageInstructions: 'Посетите julius.ai и загрузите файл CSV или Excel. Задавайте вопросы вроде «Покажи тренды продаж по месяцам». Диаграммы создаются автоматически.',
      },
    },
    categories: ['data-analytics'],
  },
  {
    name: 'Descript',
    slug: 'descript',
    logo: gf('descript.com'),
    websiteUrl: 'https://descript.com',
    description: 'Descript is an AI video and podcast editor where you edit media by editing the text transcript. Remove filler words, clone your voice with Overdub, and publish anywhere.',
    pricingType: 'FREEMIUM' as PricingType,
    pros: ['Text-based video editing', 'Auto-transcription', 'Overdub voice cloning', 'Remove filler words', 'Screen recorder included'],
    cons: ['Learning curve for new workflow', 'Resource-intensive', 'Advanced features need paid plan'],
    alternatives: ['runway', 'capcut', 'adobe-premiere'],
    usageInstructions: 'Download Descript, import your video or audio. Edit the auto-generated transcript to cut, move, or delete content. Use Remove Filler Words to clean up. Overdub fixes mistakes.',
    featured: false,
    translations: {
      ru: {
        description: 'Descript — ИИ-редактор видео и подкастов, где медиа редактируется путём редактирования текстовой расшифровки. Удаляет слова-паразиты, клонирует голос с Overdub и публикует везде.',
        pros: ['Редактирование видео на основе текста', 'Автоматическая транскрипция', 'Клонирование голоса Overdub', 'Удаление слов-паразитов', 'Встроенный рекордер экрана'],
        cons: ['Кривая обучения для нового рабочего процесса', 'Ресурсоёмкость', 'Расширенные функции требуют платного плана'],
        usageInstructions: 'Скачайте Descript, импортируйте видео или аудио. Редактируйте автоматически созданную транскрипцию для вырезания или удаления контента. Используйте Remove Filler Words для очистки. Overdub исправляет ошибки.',
      },
    },
    categories: ['video-generation', 'voice-speech'],
  },
]

async function main() {
  console.log('Seeding database...')

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat,
    })
  }
  console.log(`✓ ${categories.length} categories seeded`)

  for (const toolData of tools) {
    const { categories: catSlugs, ...data } = toolData

    const tool = await prisma.tool.upsert({
      where: { slug: data.slug },
      update: {
        ...data,
        categories: { deleteMany: {} },
      },
      create: data,
    })

    for (const slug of catSlugs) {
      const category = await prisma.category.findUnique({ where: { slug } })
      if (category) {
        await prisma.toolCategory.upsert({
          where: { toolId_categoryId: { toolId: tool.id, categoryId: category.id } },
          update: {},
          create: { toolId: tool.id, categoryId: category.id },
        })
      }
    }
  }
  console.log(`✓ ${tools.length} tools seeded with logos and translations`)
  console.log('Seeding complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
